import { getRenderer } from '@opendesign/image-icc-profile-converter'

import { PSDFileReader } from './psd-file-reader'

import type { ConvertImageOptions } from './psd-file-reader'
import type { Renderer } from '@opendesign/image-icc-profile-converter'

export type PSDFileReaderWebOptions = WithRendererOptions & {
  /** wasm image processing tool */
  renderer?: Renderer
}

export type WithRendererOptions = {
  /** Path to the .psd design file. */
  path: string

  /** Unique ID. If not passed, will be generated by UUIDv4 */
  designId?: string
}

export class PSDFileReaderWeb extends PSDFileReader {
  static async readFile(filePath: string): Promise<Uint8Array> {
    const response = await fetch(filePath)
    const buffer = await response.arrayBuffer()

    return new Uint8Array(buffer)
  }

  static async withRenderer(options: WithRendererOptions): Promise<PSDFileReaderWeb> {
    if (!PSDFileReader._renderer) {
      PSDFileReader._renderer = await getRenderer()
    }

    return new PSDFileReaderWeb({ ...options, renderer: PSDFileReader._renderer })
  }

  /**
   * Converts given PSD file into SourceDesign.
   * @constructor
   * @param {PSDFileReaderWebOptions} options
   */
  constructor(options: PSDFileReaderWebOptions) {
    const promisedData = PSDFileReaderWeb.readFile(options.path)

    super({ ...options, promisedData })
  }

  protected async _convertImage({ width, height, buff, name, iccProfile }: ConvertImageOptions): Promise<void> {
    const processedBuff = this._renderer && iccProfile ? this._renderer.render(buff, iccProfile) : buff

    const canvas = document.createElement('canvas')
    canvas.width = width
    canvas.height = height
    const context = canvas.getContext('2d')

    if (!context) {
      console.error('Error processing image: could not create context')
      return
    }

    const imageData = context.createImageData(width, height)
    const pixelData = new Uint8ClampedArray(processedBuff)
    imageData.data.set(pixelData)

    const promisedData = new Promise<Uint8Array>((resolve, reject) => {
      canvas.toBlob((blob) => {
        const fileReader = new FileReader()
        fileReader.onload = () => {
          if (!fileReader.result) {
            reject('could not read image data')
            return
          }
          const result = new Uint8Array(fileReader.result as ArrayBuffer)

          resolve(result)
        }

        if (!blob) {
          reject('')
          return
        }

        fileReader.readAsArrayBuffer(blob)
      }, 'image/png')
    })
    this._images.push({ width, height, name, promisedData })

    return
  }
}
