import path from 'path'

import { parsePsd } from '@avocode/psd-parser'
import { benchmarkAsync } from '@opendesign/octopus-common/dist/utils/benchmark-node.js'
import { displayPerf } from '@opendesign/octopus-common/dist/utils/console.js'
import chalk from 'chalk'
import { imageSize as sizeOf } from 'image-size'
import rimraf from 'rimraf'
import { v4 as uuidv4 } from 'uuid'

import { SourceDesign } from '../../entities/source/source-design.js'
import { getFilesFromDir, parseJsonFromFile } from '../../utils/files.js'
import { logger } from '../instances/logger.js'

import type { SourceImage } from '../../entities/source/source-design.js'
import type { RawComponent } from '../../typings/raw/index.js'

export type PSDFileReaderOptions = {
  /** Path to the .psd design file. */
  path: string
  /** Unique ID. If not passed, will be generated by UUIDv4 */
  designId?: string
}

/**
 * Reader that converts Adobe Photoshop .psd file into `SourceDesign` object.
 */
export class PSDFileReader {
  private _path: string
  private _designId: string
  private _sourceDesign: Promise<SourceDesign | null>

  static OUTPUT_DIR = 'workdir'
  static IMAGES_DIR = 'pictures'
  static RENDER_IMG = 'preview.png'
  static SOURCE_FILE = 'source.json'
  static PATTERNS_DIR = path.join(PSDFileReader.IMAGES_DIR, 'patterns')

  /**
   * Converts given PSD file into SourceDesign.
   * @constructor
   * @param {PSDFileReaderOptions} options
   */
  constructor(options: PSDFileReaderOptions) {
    this._path = options.path
    this._designId = options.designId || uuidv4()
    this._sourceDesign = this._initSourceDesign()
  }

  /**
   * Path to the PSD file.
   */
  get path(): string {
    return this._path
  }

  /**
   * Unique Design Identifier.
   * Passed in constructor, otherwise generated by UUIDv4.
   */
  get designId(): string {
    return this._designId
  }

  /**
   * Returns `SourceDesign` instance built from given design path using `@avocode/psd-parser`. It encapsulates all the design assets required by converter as input.
   * @returns {SourceDesign | null} Returns `SourceDesign` instance or `null` if parsing was not successful.
   */
  get sourceDesign(): Promise<SourceDesign | null> {
    return this._sourceDesign
  }

  /**
   * Cleans TempDir where source.json and source images were saved.
   */
  async cleanup(): Promise<void> {
    return new Promise((resolve, reject) => {
      rimraf(this._outDir, (error: Error | null | undefined) => {
        error ? reject(error) : resolve()
      })
    })
  }

  private get _outDir() {
    return path.join(PSDFileReader.OUTPUT_DIR, this.designId)
  }

  private get _parsePsdOptions() {
    return {
      outDir: this._outDir,
      imagesSubfolder: PSDFileReader.IMAGES_DIR,
      previewPath: path.join(this._outDir, PSDFileReader.RENDER_IMG),
      octopusFileName: 'version-2.json',
    }
  }

  private async _getSourceComponent(): Promise<RawComponent | null> {
    const { time: timeParse } = await benchmarkAsync(() => parsePsd(this.path, this._parsePsdOptions))
    logger.info(`Source file created in directory: ${chalk.yellow(this.designId)} ${displayPerf(timeParse)}`)

    const { time: timeRead, result } = await benchmarkAsync(() =>
      parseJsonFromFile<RawComponent>(path.join(this._outDir, PSDFileReader.SOURCE_FILE))
    )
    logger.info(`RawComponent prepared ${displayPerf(timeRead)}`)

    return result
  }

  private async _getImages(): Promise<SourceImage[]> {
    const imagesPath = path.join(this._outDir, PSDFileReader.IMAGES_DIR)
    const images: SourceImage[] = ((await getFilesFromDir(imagesPath)) ?? []).map((image) => {
      const name = image.name
      const relativePath = path.join(PSDFileReader.IMAGES_DIR, name)
      const imgPath = path.join(this._outDir, relativePath)
      return { name, path: imgPath }
    })

    const patterns: SourceImage[] = []
    const patternsPath = path.join(this._outDir, PSDFileReader.PATTERNS_DIR)
    const patternsResults = (await getFilesFromDir(patternsPath)) ?? []
    for (const image of patternsResults) {
      const name = image.name
      const relativePath = path.join(PSDFileReader.PATTERNS_DIR, name)
      const imgPath = path.join(this._outDir, relativePath)
      const { width, height } = sizeOf(imgPath)
      patterns.push({ name, path: imgPath, width, height })
    }

    return [...images, ...patterns]
  }

  private async _initSourceDesign(): Promise<SourceDesign | null> {
    const designId = this.designId
    const component = await this._getSourceComponent()
    if (component == null) return null
    const images = await this._getImages()
    const sourceDesign = new SourceDesign({ designId, component, images })
    return sourceDesign
  }
}
