image: node:latest

stages:
  - test

before_script:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  - yarn
  - yarn build

cache:
  paths:
    - node_modules/

lint:
  stage: test
  script:
    - yarn lint

test:
  stage: test
  artifacts: 
    paths:
      - ./my.out
  script:
    - echo "Hello" > ./my.out
