image: node:latest

stages:
  - test

before_script:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  - yarn

cache:
  paths:
    - node_modules/

lint:
  stage: test
  script:
    - yarn lint

build:
  stage: test
  script:
    - yarn build

test:
  stage: test
  script:
    - yarn test
