image: node:latest

stages:
  - test

before_script:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  - node -v
  - yarn
  - yarn build

cache:
  paths:
    - node_modules/

lint:
  stage: test
  script:
    - yarn lint

test:
  stage: test
  script:
    - yarn test
  artifacts:
    when: on_failure
    paths:
      - '**/report/*.html'
