import EventEmitter from 'events'
import path from 'path'

import { detachPromiseControls } from '@opendesign/octopus-common/dist/utils/async.js'
import { v4 as uuidv4 } from 'uuid'

import {
  getOctopusFileName,
  IMAGES_DIR_NAME,
  SOURCE_NAME,
  MANIFEST_NAME,
  STATISTICS_NAME,
} from '../../utils/exporter.js'
import { makeDir, saveFile } from '../../utils/files.js'
import { stringify } from '../../utils/stringify.js'

import type { AbstractExporter } from './abstract-exporter.js'
import type { ComponentConversionResult, DesignConversionResult } from '../conversion/design-converter.js'
import type { SourceImage } from '@opendesign/octopus-common/dist/typings/octopus-common/index.js'
import type { DetachedPromiseControls } from '@opendesign/octopus-common/dist/utils/async.js'

export type DebugExporterOptions = {
  /** Path to directory, where designs outputs should be exported. */
  tempDir: string
  /** Unique ID of the exported design. If not given, will be generated by UUIDv4. Exporter outputs will be generated into `tempDir/id` folder. */
  id?: string
}

/**
 * Exporter created to be used in manual runs.
 */
export class DebugExporter extends EventEmitter implements AbstractExporter {
  private _outputDir: Promise<string>
  private _tempDir: string
  private _assetsSaves: Promise<unknown>[]
  private _completed: DetachedPromiseControls<void>
  private _manifestPath: string | undefined
  private _statisticsPath: string | undefined

  static IMAGES_DIR_NAME = IMAGES_DIR_NAME
  static MANIFEST_NAME = MANIFEST_NAME
  static SOURCE_NAME = SOURCE_NAME
  static getOctopusFileName = getOctopusFileName

  /**
   * Exports octopus assets into given `tempDir`.
   * @constructor
   * @param {DebugExporterOptions} [options]
   */
  constructor(options: DebugExporterOptions) {
    super()
    this._tempDir = options.tempDir
    this._outputDir = this._initOutputDir(options.id)
    this._assetsSaves = []
    this._completed = detachPromiseControls<void>()
  }

  private async _initOutputDir(id?: string) {
    const tempDir = path.join(this._tempDir, typeof id === 'string' ? id : uuidv4())
    await makeDir(path.join(tempDir, IMAGES_DIR_NAME))
    return tempDir
  }

  private async _save(name: string | null, body: string | Buffer) {
    const dir = await this._outputDir
    const fullPath = path.join(dir, typeof name === 'string' ? name : uuidv4())

    const write = saveFile(fullPath, body)
    this._assetsSaves.push(write)
    await write
    return fullPath
  }

  async completed(): Promise<void> {
    await this._completed.promise
    await Promise.all(this._assetsSaves)
  }

  finalizeExport(): void {
    this.emit('octopus:manifest', this._manifestPath)
    this.emit('octopus:statistics', this._statisticsPath)
    this._completed.resolve()
  }

  getBasePath(): Promise<string> {
    return this._outputDir
  }

  /**
   * Exports given OctopusComponent
   * @param {ComponentConversionResult} conversionResult contains converted OctopusComponent or Error if conversion failed
   * @returns {Promise<string | null>} returns path to the exported OctopusComponent or `null` if conversion failed
   */
  async exportComponent(conversionResult: ComponentConversionResult): Promise<string | null> {
    if (!conversionResult.value) return Promise.resolve(null)
    const octopusPath = await this._save(getOctopusFileName(conversionResult.id), stringify(conversionResult.value))
    const sourcePath = path.join(await this._outputDir, SOURCE_NAME)
    const result = {
      id: conversionResult.id,
      time: conversionResult.time,
      error: conversionResult.error,
      octopusPath,
      sourcePath,
    }
    this.emit('octopus:component', result)
    return octopusPath
  }

  /**
   * Exports given Image into folder specified in `DebugExporter.IMAGES_DIR_NAME`
   * @param {string} name Name of the exported Image
   * @param {Uint8Array} data image data
   * @returns {Promise<string>} returns path to the exported Image
   */
  async exportImage(image: SourceImage): Promise<string> {
    const { id } = image
    const data = await image.getImageData()
    return this._save(path.join(DebugExporter.IMAGES_DIR_NAME, path.basename(id)), Buffer.from(data))
  }

  /**
   * Exports given converted OctopusManifest.
   * @param {DesignConversionResult} result contains converted OctopusManifest + conversion Time
   * @returns {Promise<string>} returns path to the OctopusManifest
   */
  async exportManifest({ manifest }: DesignConversionResult): Promise<string> {
    this._manifestPath = await this._save(MANIFEST_NAME, stringify(manifest))
    return this._manifestPath
  }

  async exportStatistics(statistics: object): Promise<string> {
    this._statisticsPath = await this._save(STATISTICS_NAME, stringify(statistics))
    return this._statisticsPath
  }
}
