export const DEFAULTS = {
  BEZIER_KNOT_TYPE: [1, 2, 4, 5],
  PATH_RECORD_TYPE: [0, 3],
  OPEN_SUBPATH_TYPE: 0,
  CLOSED_SUBPATH_TYPE: 3,
  SUBPATH_OPERATION_NONE: -1,
  LAYER_TRANSFORM: [1, 0, 0, 1, 0, 0],
  BLEND_MODE: 'NORMAL',
  RGB_COLOR_MAX_VALUE: 255,
  EFFECTS: {
    SHADOW_CHOKE: 0,
    IMAGE_FILL_TYPE: 'FILL',
    STROKE_JOIN: 'MITER',
    STROKE_CAP: 'BUTT',
    STROKE_POSITION: 'CENTER',
  },
  TEXT: {
    STYLE_BOLD: false,
    STYLE_ITALIC: false,
    STYLE_SMALLCAPS: false,
    STYLE_KERNING: true,
    LAYER_FONT_SIZE: 10,
    FONT_STYLE: 'Regular',
    FONT_STYLES: {
      '-Bold': 'Bold',
      '-BoldItalic': 'Bold Italic',
      '-Italic': 'Italic',
      '-Light': 'Light',
      '-Medium': 'Medium',
      '-Regular': 'Regular',
    },
  },
  LAYER: {
    NAME: 'Layer',
  },
  BLEND_MODES: {
    fdiv: 'DIVIDE',
    fsub: 'SUBTRACT',
    colr: 'COLOR',
    idiv: 'COLOR_BURN',
    'div ': 'COLOR_DODGE',
    dark: 'DARKEN',
    dkCl: 'DARKER_COLOR',
    diff: 'DIFFERENCE',
    smud: 'EXCLUSION',
    hLit: 'HARD_LIGHT',
    hMix: 'HARD_MIX',
    'hue ': 'HUE',
    lite: 'LIGHTEN',
    lgCl: 'LIGHTER_COLOR',
    lbrn: 'LINEAR_BURN',
    lddg: 'LINEAR_DODGE',
    lLit: 'LINEAR_LIGHT',
    'lum ': 'LUMINOSITY',
    'mul ': 'MULTIPLY',
    norm: 'NORMAL',
    over: 'OVERLAY',
    pass: 'PASS_THROUGH',
    pLit: 'PIN_LIGHT',
    'sat ': 'SATURATION',
    scrn: 'SCREEN',
    sLit: 'SOFT_LIGHT',
    vLit: 'VIVID_LIGHT',
    Nrml: 'NORMAL',
    CBrn: 'COLOR_BURN',
    CDdg: 'COLOR_DODGE',
    'Clr ': 'COLOR',
    Dfrn: 'DIFFERENCE',
    Drkn: 'DARKEN',
    // Dslv: 'dissolve', // no such type in OCTOPUS
    'H   ': 'HUE',
    HrdL: 'HARD_LIGHT',
    Lghn: 'LIGHTEN',
    Lmns: 'LUMINOSITY',
    Ovrl: 'OVERLAY',
    SftL: 'SOFT_LIGHT',
    Strt: 'SATURATION',
    Xclu: 'EXCLUSION',
    blendDivide: 'DIVIDE',
    blendSubtraction: 'SUBTRACT',
    darkerColor: 'DARKER_COLOR',
    hardMix: 'HARD_MIX',
    lighterColor: 'LIGHTER_COLOR',
    linearBurn: 'LINEAR_BURN',
    linearDodge: 'LINEAR_DODGE',
    linearLight: 'LINEAR_LIGHT',
    Mltp: 'MULTIPLY',
    pinLight: 'PIN_LIGHT',
    Scrn: 'SCREEN',
    vividLight: 'VIVID_LIGHT',
  },
} as const
