const PROP_NAMES = {
  SECTION_DIVIDER_SETTING: 'lsct',
  NESTED_SECTION_DIVIDER_SETTING: 'lsdk',
  VECTOR_MASK_SETTING1: 'vmsk',
  VECTOR_MASK_SETTING2: 'vsms',
  SOLID_COLOR_SHEET_SETTING: 'SoCo',
  GRADIENT_FILL_SETTING: 'GdFl',
  VECTOR_STROKE_CONTENT_DATA: 'vscg',
  TYPE_TOOL_OBJECT_SETTING: 'TySh',
  LAYER_NAME_SOURCE_SETTING: 'lnsr',
  VECTOR_ORIGINATION_DATA: 'vogk',
  PLACED_LAYER_DATA: 'SoLd',
  SMART_OBJECT_PLACED_LAYER_DATA: 'SoLE',
  VECTOR_STROKE_DATA: 'vstk',
  ARTBOARD_DATA: 'artb',
} as const

export default PROP_NAMES
