name: Illustrator build & publish

on:
  pull_request:
    paths:
      - 'packages/octopus-ai/**'
  push:
    branches:
      - main
    paths:
      - 'packages/octopus-ai/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: npm-illustrator
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: opendesigndev
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: install
        run: |
          yarn workspace @opendesign/octopus-common install --frozen-lockfile
          yarn workspace @opendesign/octopus-ai install --frozen-lockfile
      - name: build
        run: |
          yarn workspace @opendesign/octopus-common build
          yarn workspace @opendesign/octopus-ai build
      - name: publish
        run: |
          sed -i 's/@opendesign/@opendesigndev/g' packages/octopus-ai/package.json  
          yarn workspace @opendesigndev/octopus-ai publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
