name: Illustrator build & publish

on:
  pull_request:
    paths:
      - 'packages/octopus-ai/**'

jobs:
  build-octopus-ai:
    uses: ./.github/workflows/reusable-build.yml
    with:
      package-name: '@opendesign/octopus-ai'
    secrets: inherit
