name: Figma Plugin Squid

on:
  pull_request:
    paths:
      - 'packages/figma-plugin-squid/**'

jobs:
  build-figma-plugin-squid:
    uses: ./.github/workflows/reusable-build.yml
    with:
      package-name: '@opendesign/figma-parser'
      base-version: '3.0.0'
    secrets: inherit
