name: Illustrator build & publish

on:
  pull_request:
    paths:
      - 'packages/octopus-ai/**'
  push:
    branches:
      - main
    paths:
      - 'packages/octopus-ai/**'

jobs:
  build-octopus-ai:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/build.yml
      with: 
        package-name: '@opendesign/octopus-ai'
      secrets:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
