name: Illustrator build & publish

on:
  pull_request:
    paths:
      - 'packages/octopus-ai/**'
  push:
    branches:
      - main
    paths:
      - 'packages/octopus-ai/**'

jobs:
  build-octopus-ai:
    uses: opendesigndev/octopus/.github/workflows/reusable-build.yml@npmjs-ci
    with: 
      package-name: '@opendesign/octopus-ai'
    secrets: inherit