name: PSD build & publish

on:
  pull_request:
    paths:
      - 'packages/octopus-psd/**'
  push:
    branches:
      - main
    paths:
      - 'packages/octopus-psd/**'

jobs:
  build-octopus-psd:
    uses: opendesigndev/octopus/.github/workflows/reusable-build.yml@npmjs-ci
    with: 
      package-name: '@opendesign/octopus-psd'
      base-version: '3.1.0'
    secrets: inherit