name: Verify

on:
  pull_request:
  push:
    branches: [main]

jobs:
  verify:
    if: |
      (github.event_name == 'pull_request' && (github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'run-verify'))) || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: npm-verify
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: build
        run: yarn build
      - name: prettier
        run: yarn lint:prettier
      - name: eslint
        run: yarn lint:eslint
      - name: test
        run: yarn test
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: reports
          path: ${{ github.workspace }}/packages/**/report/*.html
