name: Verify

on:
  pull_request:
  push:
    branches: [main]

jobs:
  verify:
    if: |
      (github.event_name == 'pull_request' && (github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'run-verify'))) || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - name: install
        run: yarn
      - name: build
        run: yarn build
      - name: prettier
        run: yarn lint:prettier
      - name: eslint
        run: yarn lint:eslint
      - name: test
        run: yarn test
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: reports
          path: ${{ github.workspace }}/packages/**/report/*.html
